### ISSUE TITLE
Failure to obey MIT license

### ISSUE THREAD

**Issue by mzucker** [gosha20777/NoteShrink#2]
This project is clearly derived from https://github.com/mzucker/noteshrink but does not credit the original author (me).

The [license for the original project](https://github.com/mzucker/noteshrink/blob/master/LICENSE.txt) permits derived works and redistribution of the code as long as the original copyright notice is provided along with the software.

However the author name is changed in [this project's license](https://github.com/gosha20777/NoteShrink/blob/master/LICENSE)

Please restore my name in the LICENSE file to comply with the MIT License agreement. If you add your own code to an MIT-licensed project, it's best to just add yourself as a creator with a new year, as described [here](https://softwareengineering.stackexchange.com/questions/386582/altering-author-names-in-mit-license). 

Thanks,
-Matt

**Comment by gosha20777** [comment]
Oh. I am sorry. I found this project without lisense in the Web. Thank you for this issue!

Yes of course I will add your name and pin the link to your repo.

**Comment by gosha20777** [comment]
https://github.com/gosha20777/NoteShrink/commits/master

Look at here, please. I have add your name to the Lisense File and add the link to your repo.

**Comment by mzucker** [comment]
Thanks!
